#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

ENV_FILE="${PUSH_SERVER_ENV_FILE:-ops/deploy/push-server.env}"
LOCAL_MK_FILE="${TMUX_CHAT_LOCAL_MK_FILE:-config.local.mk}"
IOS_CONFIG_FILE="${IOS_CONFIG_FILE:-ios/TmuxChat/Config.xcconfig}"
LINUX_SERVICE_TEMPLATE_FILE="${LINUX_SERVICE_TEMPLATE_FILE:-ops/deploy/tmux-chatd.service.tailscale.example}"

APP_BUNDLE_ID_DEFAULT="$(grep -E '^app_identifier\(".*"\)' fastlane/Appfile 2>/dev/null | sed -E 's/.*"([^"]+)".*/\1/' | head -n 1 || true)"
if [[ -z "${APP_BUNDLE_ID_DEFAULT}" ]]; then
  APP_BUNDLE_ID_DEFAULT="REPLACE_WITH_APP_BUNDLE_ID"
fi

normalize_host() {
  local raw="$1"
  raw="${raw#https://}"
  raw="${raw#http://}"
  raw="${raw%%/*}"
  echo "${raw}"
}

generate_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | head -c 64
    echo
  fi
}

prompt_text() {
  local label="$1"
  local default_value="$2"
  local out_var="$3"
  local value=""
  if [[ -n "${default_value}" ]]; then
    read -r -p "${label} [${default_value}]: " value
    if [[ -z "${value}" ]]; then
      value="${default_value}"
    fi
  else
    while [[ -z "${value}" ]]; do
      read -r -p "${label}: " value
    done
  fi
  printf -v "${out_var}" "%s" "${value}"
}

prompt_secret() {
  local label="$1"
  local default_value="$2"
  local out_var="$3"
  local value=""
  if [[ -n "${default_value}" ]]; then
    read -r -s -p "${label} [直接 Enter 保留預設值]: " value
    echo
    if [[ -z "${value}" ]]; then
      value="${default_value}"
    fi
  else
    while [[ -z "${value}" ]]; do
      read -r -s -p "${label}: " value
      echo
    done
  fi
  printf -v "${out_var}" "%s" "${value}"
}

prompt_apns_key_base64() {
  local out_var="$1"
  local input=""

  echo
  echo "APNS_KEY_BASE64 設定方式："
  echo "1) 提供 .p8 檔案路徑（自動轉 base64）"
  echo "2) 直接貼上 APNS_KEY_BASE64"

  local choice=""
  while :; do
    read -r -p "請選擇 [1/2]: " choice
    [[ "${choice}" =~ ^[12]$ ]] && break
  done

  case "${choice}" in
    1)
      local p8_path=""
      while :; do
        read -r -p ".p8 檔案路徑: " p8_path
        [[ -n "${p8_path}" && -f "${p8_path}" ]] && break
        echo "找不到檔案，請重新輸入。"
      done
      input="$(base64 < "${p8_path}" | tr -d '\n')"
      ;;
    2)
      prompt_secret "貼上 APNS_KEY_BASE64" "" input
      ;;
  esac

  printf -v "${out_var}" "%s" "${input}"
}

backup_if_exists() {
  local file="$1"
  if [[ -f "${file}" ]]; then
    local backup="${file}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${file}" "${backup}"
    echo "Backed up ${file} -> ${backup}"
  fi
}

write_push_server_env() {
  mkdir -p "$(dirname "${ENV_FILE}")"
  backup_if_exists "${ENV_FILE}"
  cat > "${ENV_FILE}" <<EOF
# Generated by ops/deploy/tailscale-only-init.sh
# Tailnet HTTPS URL exposed by tailscale serve
PUSH_SERVER_PUBLIC_BASE_URL=${TS_PUSH_URL}

# Compatibility token used by tmux-chatd /notify forwarding
PUSH_SERVER_COMPAT_NOTIFY_TOKEN=${COMPAT_TOKEN}

# APNs credentials
APNS_KEY_BASE64=${APNS_KEY_BASE64}
APNS_KEY_ID=${APNS_KEY_ID}
APNS_TEAM_ID=${APNS_TEAM_ID}
APNS_BUNDLE_ID=${APNS_BUNDLE_ID}
EOF
  echo "Wrote ${ENV_FILE}"
}

write_config_local_mk() {
  backup_if_exists "${LOCAL_MK_FILE}"
  cat > "${LOCAL_MK_FILE}" <<EOF
# Generated by ops/deploy/tailscale-only-init.sh
# tmux-chatd -> push-server forwarding uses loopback on same host
PUSH_SERVER_BASE_URL = http://127.0.0.1:8790
PUSH_SERVER_COMPAT_NOTIFY_TOKEN = ${COMPAT_TOKEN}
EOF
  echo "Wrote ${LOCAL_MK_FILE}"
}

write_ios_config() {
  mkdir -p "$(dirname "${IOS_CONFIG_FILE}")"
  backup_if_exists "${IOS_CONFIG_FILE}"
  cat > "${IOS_CONFIG_FILE}" <<EOF
// Generated by ops/deploy/tailscale-only-init.sh
// iPhone connects via Tailscale HTTPS (tailnet-only)
BASE_URL = ${TS_TMUX_CHATD_URL}
PUSH_SERVER_BASE_URL = ${TS_PUSH_URL}
EOF
  echo "Wrote ${IOS_CONFIG_FILE}"
}

write_linux_service_template() {
  mkdir -p "$(dirname "${LINUX_SERVICE_TEMPLATE_FILE}")"
  backup_if_exists "${LINUX_SERVICE_TEMPLATE_FILE}"
  cat > "${LINUX_SERVICE_TEMPLATE_FILE}" <<EOF
# Generated by ops/deploy/tailscale-only-init.sh
# Copy to: /etc/systemd/system/tmux-chatd.service
[Unit]
Description=tmux-chat daemon
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/tmux-chatd
Restart=always
RestartSec=3
Environment=TMUX_CHATD_BIND_ADDR=0.0.0.0
Environment=TMUX_CHATD_PORT=8787
Environment=PUSH_SERVER_BASE_URL=http://127.0.0.1:8790
Environment=PUSH_SERVER_COMPAT_NOTIFY_TOKEN=${COMPAT_TOKEN}

[Install]
WantedBy=multi-user.target
EOF
  echo "Wrote ${LINUX_SERVICE_TEMPLATE_FILE}"
}

print_next_steps() {
  cat <<EOF

=== 下一步（共用） ===
1) 部署 push-server（Docker + env 檔）
   make push-server-deploy

2) 啟用 Tailscale HTTPS 反向代理
   tailscale serve --bg --https=8787 http://127.0.0.1:8787
   tailscale serve --bg --https=8790 http://127.0.0.1:8790
   tailscale serve status

=== macOS ===
make build
make install
make start

=== Linux ===
# 先確認 /usr/local/bin/tmux-chatd 存在，再套用 service
sudo cp ${LINUX_SERVICE_TEMPLATE_FILE} /etc/systemd/system/tmux-chatd.service
sudo systemctl daemon-reload
sudo systemctl enable --now tmux-chatd
sudo systemctl status tmux-chatd --no-pager

TS host:
  ${TS_HOST}
Control plane URL (iOS BASE_URL):
  ${TS_TMUX_CHATD_URL}
Push URL (iOS PUSH_SERVER_BASE_URL):
  ${TS_PUSH_URL}
EOF
}

main() {
  echo "=== tmux-chat Tailscale-only 一鍵初始化 ==="
  echo "將產生："
  echo "  - ${ENV_FILE}"
  echo "  - ${LOCAL_MK_FILE}"
  echo "  - ${IOS_CONFIG_FILE}"
  echo "  - ${LINUX_SERVICE_TEMPLATE_FILE}"
  echo

  local default_host
  default_host="$(hostname -s).ts.net"
  prompt_text "輸入 Tailscale 主機（例：my-host.ts.net）" "${default_host}" TS_HOST
  TS_HOST="$(normalize_host "${TS_HOST}")"
  if [[ -z "${TS_HOST}" ]]; then
    echo "Tailscale 主機不可為空" >&2
    exit 1
  fi

  local default_token
  default_token="$(generate_token)"
  prompt_secret "PUSH_SERVER_COMPAT_NOTIFY_TOKEN" "${default_token}" COMPAT_TOKEN
  prompt_apns_key_base64 APNS_KEY_BASE64
  prompt_text "APNS_KEY_ID" "" APNS_KEY_ID
  prompt_text "APNS_TEAM_ID" "" APNS_TEAM_ID
  prompt_text "APNS_BUNDLE_ID" "${APP_BUNDLE_ID_DEFAULT}" APNS_BUNDLE_ID

  TS_TMUX_CHATD_URL="https://${TS_HOST}:8787"
  TS_PUSH_URL="https://${TS_HOST}:8790"

  if [[ -z "${COMPAT_TOKEN}" || -z "${APNS_KEY_BASE64}" || -z "${APNS_KEY_ID}" || -z "${APNS_TEAM_ID}" || -z "${APNS_BUNDLE_ID}" ]]; then
    echo "必要欄位不可為空，初始化中止。" >&2
    exit 1
  fi

  write_push_server_env
  write_config_local_mk
  write_ios_config
  write_linux_service_template
  print_next_steps
}

main "$@"
